name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci-job:
    name: CI
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: ["20.x"]
      fail-fast: true
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/ci-job.yml
    with:
      os: ${{ matrix.os }}
      node-version: ${{ matrix.node-version }}
      github-event-name: ${{ github.event_name }}
    secrets: inherit